version: '3.7'
services:
  elasticsearch:
      container_name: elastic
      build: "es"
      volumes:
        - ./es/data:/tmp
      ports:
        - 9200:9200
      environment:
        discovery.type: single-node

  kibana:
      container_name: kibana
      image: kibana:7.7.1
      links:
        - elasticsearch
      ports:
        - 5601:5601

